# This workflow is designed to build and deploy your project to GitHub Pages.
# It is configured to run ONLY on pushes to the main/master branch or when manually triggered.
name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push events but only for the main and master branches
  push:
    branches: [ main, master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allows only one concurrent deployment, skipping runs queued between the run in-progress and the latest queued.
# However, do NOT cancel in-progress runs as we want each deployment to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        # Using --silent to keep logs clean. CI=false is often needed for React apps.
        run: npm run build --silent
        env:
          CI: false
          
      - name: Setup Pages
        # This action configures the Pages environment for the deployment.
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        # This action uploads the build output as a GitHub Pages artifact.
        uses: actions/upload-pages-artifact@v3
        with:
          # Specifies the directory to upload. This should match your build output folder.
          path: './build'

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the build job completing successfully.
    
    # ✅ KEY FIX: This condition ensures the deploy job ONLY runs on a push to main/master.
    # It prevents the job from running on pull requests, even if the trigger were changed.
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
